import type { ShoppingList, ShoppingListItem } from '@/types/domain';

export type GroceryService = 
  | 'glovo' 
  | 'uberEats' 
  | 'wolt' 
  | 'gorillas' 
  | 'getir' 
  | 'flink'
  | 'instacart' 
  | 'amazonFresh' 
  | 'csv' 
  | 'text';

export interface ExportConfig {
  name: string;
  icon: string;
  color: string;
  description: string;
  region: 'EU' | 'US' | 'Global';
}

export const GROCERY_SERVICES: Record<GroceryService, ExportConfig> = {
  glovo: {
    name: 'Glovo',
    icon: '🟡',
    color: 'oklch(0.8 0.18 85)',
    description: 'Fast delivery across Europe',
    region: 'EU',
  },
  uberEats: {
    name: 'Uber Eats',
    icon: '🍔',
    color: 'oklch(0.2 0.02 120)',
    description: 'Grocery delivery worldwide',
    region: 'Global',
  },
  wolt: {
    name: 'Wolt',
    icon: '💙',
    color: 'oklch(0.55 0.15 240)',
    description: 'Popular in Northern & Central Europe',
    region: 'EU',
  },
  gorillas: {
    name: 'Gorillas',
    icon: '🦍',
    color: 'oklch(0.25 0.01 270)',
    description: '10-minute grocery delivery',
    region: 'EU',
  },
  getir: {
    name: 'Getir',
    icon: '🟣',
    color: 'oklch(0.45 0.18 290)',
    description: 'Quick grocery delivery',
    region: 'EU',
  },
  flink: {
    name: 'Flink',
    icon: '⚡',
    color: 'oklch(0.75 0.20 160)',
    description: 'Express grocery delivery',
    region: 'EU',
  },
  instacart: {
    name: 'Instacart',
    icon: '🛒',
    color: 'oklch(0.55 0.15 145)',
    description: 'Same-day grocery delivery',
    region: 'US',
  },
  amazonFresh: {
    name: 'Amazon Fresh',
    icon: '📦',
    color: 'oklch(0.65 0.15 45)',
    description: 'Amazon grocery delivery',
    region: 'Global',
  },
  csv: {
    name: 'CSV File',
    icon: '📊',
    color: 'oklch(0.55 0.12 150)',
    description: 'Spreadsheet format',
    region: 'Global',
  },
  text: {
    name: 'Plain Text',
    icon: '📝',
    color: 'oklch(0.5 0.01 220)',
    description: 'Simple text file',
    region: 'Global',
  },
};

function formatQuantity(item: ShoppingListItem): string {
  if (item.unit === 'pieces') {
    return `${item.total_quantity} pieces`;
  }
  
  if (item.total_quantity >= 1000) {
    const kg = item.total_quantity / 1000;
    return item.unit === 'g' ? `${kg.toFixed(2)} kg` : `${kg.toFixed(2)} L`;
  }
  
  return `${item.total_quantity}${item.unit}`;
}

export function exportToGlovo(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `🛍️ ${item.display_name} - ${formatQuantity(item)}`)
    .join('\n');
  
  const content = `🟡 Glovo Shopping List - Gurmaio
${new Date().toLocaleDateString()}

${items}

📊 Summary:
• ${shoppingList.summary.total_items} items
• Est. Total: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

💡 Tip: Search for each item in the Glovo app under "Groceries" or your preferred supermarket.`;
  
  copyToClipboard(content, '✅ Glovo list copied! Paste it into your Glovo app.');
}

export function exportToUberEats(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `• ${item.display_name} (${formatQuantity(item)})`)
    .join('\n');
  
  const content = `🍔 Uber Eats Grocery List
Generated by Gurmaio - ${new Date().toLocaleDateString()}

${items}

Summary:
Items: ${shoppingList.summary.total_items}
Estimated: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

Open Uber Eats → Grocery → Search for each item`;
  
  copyToClipboard(content, '✅ Uber Eats list copied! Open the app and start shopping.');
}

export function exportToWolt(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `${item.display_name} | ${formatQuantity(item)} | ~€${item.estimated_price_eur.toFixed(2)}`)
    .join('\n');
  
  const content = `💙 Wolt Shopping List - Gurmaio
${new Date().toLocaleDateString()}

${items}

Total: ${shoppingList.summary.total_items} items
Estimated Cost: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

📱 Open Wolt app → Choose your supermarket → Add items to cart`;
  
  copyToClipboard(content, '✅ Wolt list copied! Paste in your Wolt app.');
}

export function exportToGorillas(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `🦍 ${item.display_name} - ${formatQuantity(item)}`)
    .join('\n');
  
  const content = `🦍 Gorillas Quick List - Gurmaio
${new Date().toLocaleDateString()}

${items}

📦 ${shoppingList.summary.total_items} items
💶 €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)} estimated

⚡ 10-minute delivery! Search for items in the Gorillas app.`;
  
  copyToClipboard(content, '✅ Gorillas list copied! Ready for quick delivery.');
}

export function exportToGetir(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `🟣 ${item.display_name} (${formatQuantity(item)})`)
    .join('\n');
  
  const content = `🟣 Getir Shopping List
Gurmaio Meal Plan - ${new Date().toLocaleDateString()}

${items}

Summary: ${shoppingList.summary.total_items} items | €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

Open Getir app and search for each item for quick delivery!`;
  
  copyToClipboard(content, '✅ Getir list copied! Open the app to shop.');
}

export function exportToFlink(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `⚡ ${item.display_name} - ${formatQuantity(item)}`)
    .join('\n');
  
  const content = `⚡ Flink Express Shopping - Gurmaio
${new Date().toLocaleDateString()}

${items}

Total Items: ${shoppingList.summary.total_items}
Est. Cost: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

🚀 Express delivery in minutes! Add items in the Flink app.`;
  
  copyToClipboard(content, '✅ Flink list copied! Ready for express delivery.');
}

export function exportToInstacart(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `${item.display_name} - ${formatQuantity(item)}`)
    .join('\n');
  
  const content = `🛒 Instacart Shopping List - Gurmaio
${new Date().toLocaleDateString()}

${items}

Total Items: ${shoppingList.summary.total_items}
Estimated Cost: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

Copy these items into your Instacart cart or search for each item in the app.`;
  
  copyToClipboard(content, '✅ Instacart list copied! Paste it into your Instacart app.');
}

export function exportToAmazonFresh(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `• ${item.display_name} (${formatQuantity(item)})`)
    .join('\n');
  
  const content = `📦 Amazon Fresh Shopping List
Generated by Gurmaio on ${new Date().toLocaleDateString()}

${items}

Total: ${shoppingList.summary.total_items} items | Est. €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

Search for each item in Amazon Fresh or Whole Foods.`;
  
  copyToClipboard(content, '✅ Amazon Fresh list copied! Paste it into your Amazon app.');
}

export function exportToCSV(shoppingList: ShoppingList): void {
  const headers = 'Item Name,Quantity,Unit,Estimated Price (EUR)';
  
  const rows = shoppingList.items.map(item => 
    `"${item.display_name}",${item.total_quantity},${item.unit},${item.estimated_price_eur.toFixed(2)}`
  );
  
  const csv = [headers, ...rows].join('\n');
  
  downloadFile(csv, `gurmaio-shopping-list-${Date.now()}.csv`, 'text/csv');
}

export function exportToText(shoppingList: ShoppingList): void {
  const content = `GURMAIO SHOPPING LIST
Generated: ${new Date().toLocaleString()}
Plan ID: ${shoppingList.plan_id}

${'='.repeat(50)}

${shoppingList.items.map((item, index) => 
  `${(index + 1).toString().padStart(2, '0')}. ${item.display_name}
    Quantity: ${formatQuantity(item)}
    Est. Price: €${item.estimated_price_eur.toFixed(2)}`
).join('\n\n')}

${'='.repeat(50)}

SUMMARY
-------
Total Items: ${shoppingList.summary.total_items}
Plan Cost: €${shoppingList.summary.plan_cost_eur.toFixed(2)}
Shopping Cost: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}
Waste/Extra: €${shoppingList.summary.waste_cost_eur.toFixed(2)}

${'='.repeat(50)}

Note: Prices are estimates based on regional averages.
Actual costs may vary by store and location.`;
  
  downloadFile(content, `gurmaio-shopping-list-${Date.now()}.txt`, 'text/plain');
}

function copyToClipboard(text: string, successMessage: string): void {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(text)
      .then(() => {
        if (typeof window !== 'undefined' && 'toast' in window) {
          (window as any).showToast?.(successMessage);
        }
      })
      .catch((err) => {
        console.error('Failed to copy to clipboard:', err);
        fallbackCopy(text);
      });
  } else {
    fallbackCopy(text);
  }
}

function fallbackCopy(text: string): void {
  const textArea = document.createElement('textarea');
  textArea.value = text;
  textArea.style.position = 'fixed';
  textArea.style.left = '-999999px';
  textArea.style.top = '-999999px';
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();
  
  try {
    document.execCommand('copy');
    if (typeof window !== 'undefined' && 'toast' in window) {
      (window as any).showToast?.('Copied to clipboard!');
    }
  } catch (err) {
    console.error('Fallback copy failed:', err);
  }
  
  document.body.removeChild(textArea);
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
  
  if (typeof window !== 'undefined' && 'toast' in window) {
    (window as any).showToast?.(`Downloaded ${filename}`);
  }
}

export function exportShoppingList(shoppingList: ShoppingList, service: GroceryService): void {
  switch (service) {
    case 'glovo':
      exportToGlovo(shoppingList);
      break;
    case 'uberEats':
      exportToUberEats(shoppingList);
      break;
    case 'wolt':
      exportToWolt(shoppingList);
      break;
    case 'gorillas':
      exportToGorillas(shoppingList);
      break;
    case 'getir':
      exportToGetir(shoppingList);
      break;
    case 'flink':
      exportToFlink(shoppingList);
      break;
    case 'instacart':
      exportToInstacart(shoppingList);
      break;
    case 'amazonFresh':
      exportToAmazonFresh(shoppingList);
      break;
    case 'csv':
      exportToCSV(shoppingList);
      break;
    case 'text':
      exportToText(shoppingList);
      break;
  }
}
